import { Theme, ThemeColor } from './types';

export const themes: Record<ThemeColor, Theme> = {
  fuchsia: {
    appBg: 'bg-gray-950',
    chatWindowBg: 'bg-gray-900',
    header: {
      headerBg: 'bg-gray-800',
      headerText: 'text-gray-100',
      titleText: 'text-fuchsia-400',
    },
    message: {
      sentBg: 'bg-gradient-to-br from-fuchsia-600 to-purple-600',
      sentText: 'text-gray-100',
      receivedBg: 'bg-gray-700',
      receivedText: 'text-gray-100',
      timestampText: 'text-fuchsia-200',
    },
    messageInput: {
      inputContainerBg: 'bg-gray-800',
      inputBg: 'bg-gray-700',
      inputText: 'text-gray-100',
      inputPlaceholder: 'placeholder-gray-400',
      inputRing: 'focus:ring-fuchsia-500',
      sendButtonBg: 'bg-fuchsia-600',
      sendButtonHoverBg: 'hover:bg-fuchsia-700',
    },
    drawer: {
      drawerBg: 'bg-gray-900',
      drawerText: 'text-gray-100',
      drawerHeaderBg: 'border-gray-800',
      inputBg: 'bg-gray-700',
      buttonColor: 'bg-fuchsia-600',
      accentColor: 'text-fuchsia-400 focus:ring-fuchsia-500',
    },
    switcher: {
      containerBg: 'bg-gray-900/70',
      activeBg: 'bg-fuchsia-600',
      activeText: 'text-white',
      inactiveText: 'text-fuchsia-300',
      inactiveHoverBg: 'hover:bg-fuchsia-500/20',
    },
  },
  cyan: {
    appBg: 'bg-gray-950',
    chatWindowBg: 'bg-gray-900',
    header: {
      headerBg: 'bg-gray-800',
      headerText: 'text-gray-100',
      titleText: 'text-cyan-400',
    },
    message: {
      sentBg: 'bg-gradient-to-br from-cyan-500 to-blue-500',
      sentText: 'text-white',
      receivedBg: 'bg-gray-700',
      receivedText: 'text-gray-100',
      timestampText: 'text-cyan-200',
    },
    messageInput: {
      inputContainerBg: 'bg-gray-800',
      inputBg: 'bg-gray-700',
      inputText: 'text-gray-100',
      inputPlaceholder: 'placeholder-gray-400',
      inputRing: 'focus:ring-cyan-500',
      sendButtonBg: 'bg-cyan-600',
      sendButtonHoverBg: 'hover:bg-cyan-700',
    },
    drawer: {
      drawerBg: 'bg-gray-900',
      drawerText: 'text-gray-100',
      drawerHeaderBg: 'border-gray-800',
      inputBg: 'bg-gray-700',
      buttonColor: 'bg-cyan-600',
      accentColor: 'text-cyan-400 focus:ring-cyan-500',
    },
    switcher: {
      containerBg: 'bg-gray-900/70',
      activeBg: 'bg-cyan-600',
      activeText: 'text-white',
      inactiveText: 'text-cyan-300',
      inactiveHoverBg: 'hover:bg-cyan-500/20',
    },
  },
  emerald: {
    appBg: 'bg-gray-950',
    chatWindowBg: 'bg-gray-900',
    header: {
      headerBg: 'bg-gray-800',
      headerText: 'text-gray-100',
      titleText: 'text-emerald-400',
    },
    message: {
      sentBg: 'bg-gradient-to-br from-emerald-600 to-green-600',
      sentText: 'text-white',
      receivedBg: 'bg-gray-700',
      receivedText: 'text-gray-100',
      timestampText: 'text-emerald-200',
    },
    messageInput: {
      inputContainerBg: 'bg-gray-800',
      inputBg: 'bg-gray-700',
      inputText: 'text-gray-100',
      inputPlaceholder: 'placeholder-gray-400',
      inputRing: 'focus:ring-emerald-500',
      sendButtonBg: 'bg-emerald-600',
      sendButtonHoverBg: 'hover:bg-emerald-700',
    },
    drawer: {
      drawerBg: 'bg-gray-900',
      drawerText: 'text-gray-100',
      drawerHeaderBg: 'border-gray-800',
      inputBg: 'bg-gray-700',
      buttonColor: 'bg-emerald-600',
      accentColor: 'text-emerald-400 focus:ring-emerald-500',
    },
    switcher: {
      containerBg: 'bg-gray-900/70',
      activeBg: 'bg-emerald-600',
      activeText: 'text-white',
      inactiveText: 'text-emerald-300',
      inactiveHoverBg: 'hover:bg-emerald-500/20',
    },
  },
  orange: {
    appBg: 'bg-gray-950',
    chatWindowBg: 'bg-gray-900',
    header: {
      headerBg: 'bg-gray-800',
      headerText: 'text-gray-100',
      titleText: 'text-orange-400',
    },
    message: {
      sentBg: 'bg-gradient-to-br from-orange-500 to-amber-500',
      sentText: 'text-white',
      receivedBg: 'bg-gray-700',
      receivedText: 'text-gray-100',
      timestampText: 'text-orange-200',
    },
    messageInput: {
      inputContainerBg: 'bg-gray-800',
      inputBg: 'bg-gray-700',
      inputText: 'text-gray-100',
      inputPlaceholder: 'placeholder-gray-400',
      inputRing: 'focus:ring-orange-500',
      sendButtonBg: 'bg-orange-600',
      sendButtonHoverBg: 'hover:bg-orange-700',
    },
    drawer: {
      drawerBg: 'bg-gray-900',
      drawerText: 'text-gray-100',
      drawerHeaderBg: 'border-gray-800',
      inputBg: 'bg-gray-700',
      buttonColor: 'bg-orange-600',
      accentColor: 'text-orange-400 focus:ring-orange-500',
    },
    switcher: {
      containerBg: 'bg-gray-900/70',
      activeBg: 'bg-orange-600',
      activeText: 'text-white',
      inactiveText: 'text-orange-300',
      inactiveHoverBg: 'hover:bg-orange-500/20',
    },
  },
  rose: {
    appBg: 'bg-gray-950',
    chatWindowBg: 'bg-gray-900',
    header: {
      headerBg: 'bg-gray-800',
      headerText: 'text-gray-100',
      titleText: 'text-rose-400',
    },
    message: {
      sentBg: 'bg-gradient-to-br from-rose-600 to-pink-600',
      sentText: 'text-white',
      receivedBg: 'bg-gray-700',
      receivedText: 'text-gray-100',
      timestampText: 'text-rose-200',
    },
    messageInput: {
      inputContainerBg: 'bg-gray-800',
      inputBg: 'bg-gray-700',
      inputText: 'text-gray-100',
      inputPlaceholder: 'placeholder-gray-400',
      inputRing: 'focus:ring-rose-500',
      sendButtonBg: 'bg-rose-600',
      sendButtonHoverBg: 'hover:bg-rose-700',
    },
    drawer: {
      drawerBg: 'bg-gray-900',
      drawerText: 'text-gray-100',
      drawerHeaderBg: 'border-gray-800',
      inputBg: 'bg-gray-700',
      buttonColor: 'bg-rose-600',
      accentColor: 'text-rose-400 focus:ring-rose-500',
    },
    switcher: {
      containerBg: 'bg-gray-900/70',
      activeBg: 'bg-rose-600',
      activeText: 'text-white',
      inactiveText: 'text-rose-300',
      inactiveHoverBg: 'hover:bg-rose-500/20',
    },
  },
};